const fs = require('fs');

const nuevas = [
  // ===== COMPORTAMIENTO Y DROGAS =====
  {id:231,cat:'seguridad',q:'¿Cuáles son los efectos fisiológicos de las drogas depresoras (como la marihuana) en el conductor?',ops:['Aumentan la concentración y atención','Alteran enormemente la percepción del tiempo y la distancia (espacio), además de disminuir los reflejos y producir relajación peligrosa al volante','Mejoran el tiempo de reacción','No producen ningún efecto si se consumen en pequeñas cantidades'],r:1,exp:'El cannabis (marihuana) es depresor del sistema nervioso: altera el cálculo correcto del tiempo y las distancias (el conductor percibe el tiempo más lento y cree ir despacio), aumenta el tiempo de reacción e induce fuerte somnolencia y pérdida de atención.'},
  {id:232,cat:'seguridad',q:'¿Cuáles son los efectos de las drogas estimulantes (como la cocaína) en el conductor?',ops:['Reducen la agresividad y dan calma','Provocan sueño extremo inmediato','Generan sobrevaloración de las propias capacidades, impulsividad, agresividad al volante, exceso de velocidad y conductas altamente temerarias','Aumentan la precisión al frenar'],r:2,exp:'La cocaína u otros estimulantes eliminan la percepción natural de cansancio, haciendo creer al conductor que domina todo perfectamente (falsa seguridad). Son responsables de conductas muy agresivas, choques por exceso de velocidad e impaciencia en los cruces.'},
  {id:233,cat:'seguridad',q:'Si un médico le receta antihistamínicos (medicamentos para la alergia), ¿puede conducir?',ops:['Sí, porque son medicamentos legales','Debe leer atentamente el prospecto o consultar al médico, ya que muchos de estos medicamentos provocan somnolencia severa','Solo puede conducir de día','Sí, los medicamentos no afectan al cerebro'],r:1,exp:'Medicamentos comunes como antigripales, antialérgicos, analgésicos fuertes y psicofármacos pueden causar somnolencia, mareos o visión borrosa. Todo conductor debe informarse siempre sobre los efectos adversos antes de conducir bajo medicación.'},
  {id:234,cat:'seguridad',q:'Usted es testigo de que un ciclista ha caído y sangra abundantemente por una pierna. ¿Qué debe hacer?',ops:['Hacer un torniquete con una soga fuertemente','Poner un apósito estéril o paño limpio y presionar fuertemente con la mano sobre la herida para detener la hemorragia, esperando la ambulancia','Lavar la herida con alcohol inmediatamente','Subirlo a su vehículo particular para llevarlo rápido al hospital'],r:1,exp:'Ante una hemorragia abundante, la medida vital de primeros auxilios es la "compresión directa": usar un paño limpio y hacer presión sobre el punto sangrante continuamente para que coagule hasta que lleguen los profesionales.'},
  
  // ===== PRIORIDAD DE PASO =====
  {id:235,cat:'normas',q:'¿Quién tiene preferencia de paso cuando se aproxima un vehículo de emergencia usando señales audibles y visuales?',ops:['El vehículo que va por la avenida principal','El vehículo de emergencia en todos los casos: usted debe cederle el paso desviándose hacia el borde derecho o deteniéndose si es preciso','El vehículo más pesado','Los peatones que cruzan en ese momento'],r:1,exp:'Frente a ambulancias, bomberos o patrullas con sirena/baliza, rige la regla de prioridad absoluta. Todos los conductores deben orillarse y liberar el centro de la vía o el carril rápido para que pasen, deteniéndose completamente si no hay espacio.'},
  {id:236,cat:'normas',q:'¿Quién tiene preferencia entre un peatón cruzando por un paso de cebra y un vehículo que se aproxima?',ops:['El vehículo si viene rápido','El vehículo, porque los pasos peatonales son solo advertencias','El peatón siempre tiene preferencia absoluta en un paso peatonal (cebra) que no tiene semáforo ni carabinero','El que primero llegue al cruce'],r:2,exp:'En un cruce regulado por "rayas blancas transversales" (paso de cebra) o demarcaciones peatonales (y sin semáforo), el peatón goza del derecho preferente de paso de manera incondicional. El auto DEBE detenerse si el peatón ya pisó la calzada o muestra intención.'},
  {id:237,cat:'normas',q:'Al virar (doblar) a la izquierda o a la derecha en una intersección con semáforo en verde, usted encuentra peatones cruzando la calle hacia la cual usted dobló. ¿Quién tiene preferencia?',ops:['Usted, porque su semáforo estaba en verde al doblar','El peatón tiene la preferencia de paso. El conductor que vira debe detenerse y esperar a que terminen de cruzar','El que toca la bocina primero','Los ciclistas, pero no los peatones'],r:1,exp:'Regla de oro: Todo vehículo que realice un viraje en un cruce regulado por semáforo, PIERDE LA PREFERENCIA respecto de los peatones que cruzan la vía a la que el conductor ingresa. El semáforo verde para virar no anula el paso peatonal.'},
  
  // ===== TECNICAS AVANZADAS =====
  {id:238,cat:'manejo',q:'¿Por qué se debe mantener una marcha puesta (evitar punto muerto) al circular en descensos prolongados?',ops:['Porque ahorra mucha bencina ir en punto muerto','Porque mantener un cambio puesto permite utilizar la compresión del motor como "freno de motor", evitando sobrecalentar y quemar los frenos de servicio (pedal)','Porque lo prohíbe la señalética','Porque el auto iría más rápido sin ruido'],r:1,exp:'Circular cuesta abajo en neutro (punto muerto) o pisando el embrague es gravísimo. Se anula el freno que hace el motor. El auto agarrará vuelo por la pendiente obligando al conductor a pisar excesivamente los frenos hasta sobrecalentarlos (fading) o quemarlos.'},
  {id:239,cat:'manejo',q:'¿Cómo se debe mirar a través de los espejos retrovisores?',ops:['Mirar fijamente el espejo central todo el tiempo','Mirar los espejos de forma frecuente (cada 5 a 10 segundos), pero con vistazos rápidos para no desatender el frente','Solo mirarlos al momento exacto de doblar o cambiar de pista','Solo cuando el acompañante avise'],r:1,exp:'El conductor defensivo mantiene controlada toda su burbuja de espacio. Debe dar vistazos rápidos (escaneo) a los espejos laterales y al retrovisor central constantemente (cada pocos segundos) para saber qué hay alrededor, antes de que ocurra una emergencia.'},
  {id:240,cat:'manejo',q:'Usted conduce a 90 km/h por una carretera donde se permite 100 km/h, y se da cuenta de que el vehículo detrás suyo lo sigue a una distancia excesivamente corta (pegado a su parachoques). ¿Qué debe hacer?',ops:['Frenar de golpe para asustarlo','Acelerar a 110 km/h para alejarse','Ignorarlo y seguir igual','Aumentar su propia distancia de seguimiento respecto al vehículo que va DELANTE de usted, para tener más espacio de frenada suave si ocurre un imprevisto, y dejar que el de atrás lo adelante cuando pueda'],r:3,exp:'Tener un "acosador" detrás (tailgating) es muy peligroso. Como no puede controlar lo que él hace, la mejor defensa es aumentar drásticamente su propia distancia frontal. Así, si tiene que frenar, podrá hacerlo muy suavemente sin obligar al que va pegado a chocarlo.'},
  
  // ===== SENALES VARIAS =====
  {id:241,cat:'senales',q:'¿Qué forma y color tiene generalmente una señal de REGLAMENTACIÓN u OBLIGACIÓN (como "Mantenga su derecha" o "Dirección obligatoria")?',ops:['Triangular de color amarillo','Circular, de fondo azul y orla o símbolo blanco (también pueden ser rectangulares azules)','Octagonal roja','Verde rectangular'],r:1,exp:'Las señales reglamentarias de obligación, que exigen acciones ineludibles al conductor (como ir obligatoriamente en un sentido, encender luces, usar cadenas), suelen ser redondas con fondo azul y símbolos en blanco.'},
  {id:242,cat:'senales',q:'Si hay una señal de VELOCIDAD MÁXIMA que indica "60", junto a otra que dice "Zona de Escuela", ¿a qué velocidad máxima debe circular durante los horarios de entrada/salida de estudiantes?',ops:['60 km/h porque la señal de velocidad prevalece','30 km/h, por ley en zonas y horarios escolares la velocidad se reduce, independientemente de la señal de la vía principal','50 km/h','El límite se anula por la de escuela, puede ir más lento'],r:1,exp:'La Ley de Tránsito es clara: en zonas de escuelas, colegios o parques con afluencia infantil, durante las horas de funcionamiento o entrada/salida, el límite de velocidad legal absoluto y obligatorio es de 30 km/h.'},
  {id:243,cat:'senales',q:'¿Qué indica una luz ROJA encendida de forma constante en el tablero, con el símbolo de una BATERÍA (símbolo + y -)?',ops:['Que la batería está cargada al máximo','Que hay un problema en el sistema eléctrico de carga, el alternador no está enviando corriente a la batería y el auto se apagará pronto','Que faltan líquidos a la batería','Que el vehículo gasta poco combustible'],r:1,exp:'Si el símbolo de la batería rojo no se apaga tras encender el motor (o se enciende andando), significa falla grave en el sistema de recarga (el alternador dejó de cargar, se cortó la correa, etc.). El vehículo está funcionando con la poca reserva eléctrica de la batería y se parará.'},
  {id:244,cat:'senales',q:'¿Cuál es el significado de las líneas de calzada con forma de CUADRICULADO AMARILLO (cruces)?',ops:['Indica que es un paso de peatones para colegios','Indica que está prohibido ingresar a esa intersección si las condiciones del tráfico no permiten salir de ella libremente, para no bloquear los cruces viales','Que es zona exclusiva para bomberos','Punto de adelantamiento'],r:1,exp:'Estas demarcaciones amarillas en forma de red (cuadrícula) se pintan en intersecciones muy transitadas. Significa: "No bloquee el cruce". Nunca pise el área amarilla a menos que tenga asegurado el espacio al otro lado de la calle para salir completamente del cruce.'},
  
  // ===== MISC NORMAS =====
  {id:245,cat:'normas',q:'Respecto del chaleco reflectante amarillo, ¿qué exige la ley actual en Chile?',ops:['Que debe estar en el portamaletas en caso de pana','Que es obligatorio portarlo siempre dentro del habitáculo (cabina) para poder ponérselo ANTES de bajar del vehículo en caso de emergencia en ruta','Solo es obligatorio para camiones','No es obligatorio, solo recomendado'],r:1,exp:'El chaleco amarillo de alta visibilidad es obligatorio. Además, la norma exige que debe ir en el interior del auto (como la guantera o debajo del asiento) porque su objetivo es que usted se baje del auto con el chaleco ya puesto y pueda ser visto.'},
  {id:246,cat:'normas',q:'¿Qué establece la ley con respecto al uso de teléfonos móviles durante la conducción (Ley No Chat)?',ops:['Prohíbe la conducción de cualquier vehículo mientras se manipule un celular o cualquier dispositivo electrónico que no venga incorporado de fábrica. Se califica como Infracción Gravísima','Se puede usar solo en semáforos rojos','Está permitido solo enviar audios de voz','Se puede usar para mapas si lo sostiene con una mano'],r:0,exp:'La Ley No Chat endureció las penas. Es una falta GRAVÍSIMA (multa alta y suspensión de licencia de 5 a 45 días) manipular el celular mientras conduce, incluso detenido en un semáforo rojo o señal de PARE. Si usa GPS debe dejar fijado el aparato a la vista.'},
  {id:247,cat:'normas',q:'En relación a los motociclistas en la calzada, los conductores de automóviles deben recordar que:',ops:['Son menos importantes que los autos','Pueden acelerar y frenar más lentamente','Son de tamaño reducido, por lo que es más fácil no verlos (caen en puntos ciegos) y cuesta más estimar la distancia y velocidad a la que se acercan','Tienen menos derechos en los cruces'],r:2,exp:'El perfil frontal de una moto es pequeño. El ojo humano puede fallar al calcular a qué distancia viene una moto o si se mueve rápido. Además, las motos caben fácilmente en los grandes ángulos muertos de los espejos del automóvil.'},
  {id:248,cat:'normas',q:'Al circular por carreteras con doble pista por sentido, si usted viaja a velocidad normal/lenta sin intención de adelantar, usted DEBE:',ops:['Circular estrictamente por la pista derecha, dejando libre la izquierda para los adelantamientos y vehículos más veloces','Circular por el medio de las dos pistas','Circular por la izquierda porque es más segura','Circular por la pista que quiera, es libre'],r:0,exp:'Una norma básica mundial de autopistas: "Mantenga su derecha". El carril izquierdo es EXCLUSIVAMENTE para sobrepasar a otros vehículos o porque el carril derecho está obstruido. Tras adelantar, debe volver a la pista derecha.'},
  {id:249,cat:'normas',q:'¿En qué consiste el "Efecto Submarino" provocado por el mal uso del cinturón de seguridad?',ops:['En ahogarse dentro del auto si cae al agua','En usar cinturones falsos','Cuando el ocupante lleva el cinturón holgado, o va recostado en el asiento (muy echado atrás), de modo que al chocar su cuerpo se desliza por debajo de la cinta abdominal del cinturón estrellándose contra el tablero','En deslizarse por una calle inundada'],r:2,exp:'El cinturón no sirve si la postura es mala. Si se recuesta excesivamente en el asiento o usa cojines sueltos, en caso de choque frontal brusco su cuerpo no será retenido por la banda pélvica, deslizándose hacia abajo por debajo del cinturón (como un submarino hundiendo).'},
  {id:250,cat:'normas',q:'Si observa un accidente donde un automóvil chocó contra un poste y hay cables eléctricos sueltos sobre el vehículo con personas dentro. ¿Qué les debe indicar?',ops:['Que abran las puertas y corran hacia fuera rápido','Que se tiren rodando al suelo para no tocar los neumáticos','Que no toquen NINGUNA parte metálica del auto ni intenten bajar, deben permanecer adentro porque los neumáticos aíslan el vehículo del suelo; que esperen a equipos de rescate','Que echen agua desde adentro'],r:2,exp:'Si caen cables eléctricos vivos sobre el coche, el exterior se electrifica pero el interior es seguro debido a que las gomas de los neumáticos aíslan el suelo (efecto jaula de Faraday). Si pisan tierra tocando el metal del coche a la vez, morirían electrocutados instantáneamente.'}
];

let content = fs.readFileSync('preguntas.js', 'utf8');
let nuevasLineas = '';
nuevas.forEach(p => {
  const ops = JSON.stringify(p.ops);
  nuevasLineas += '  { id:' + p.id + ', categoria:"' + p.cat + '", pregunta:"' + p.q + '", opciones:' + ops + ', respuesta:' + p.r + ', explicacion:"' + p.exp + '" },\n';
});
content = content.replace('];\n\nconst CATEGORIAS', nuevasLineas + '];\n\nconst CATEGORIAS');
fs.writeFileSync('preguntas.js', content, 'utf8');

let html = fs.readFileSync('index.html', 'utf8');
html = html.replace('230 preguntas', '250 preguntas');
html = html.replace('170 preguntas', '250 preguntas'); // fallback
html = html.replace('Mas de 170 preguntas', 'Mas de 250 preguntas'); 
fs.writeFileSync('index.html', html, 'utf8');

console.log('Agregadas ' + nuevas.length + ' preguntas.');
