const fs = require('fs');

const nuevas = [
  // ===== NORMAS Y LEYES (continuación) =====
  {id:211,cat:'normas',q:'¿Cuándo está permitido adelantar por la DERECHA en Chile?',ops:['En carreteras de doble vía siempre','Nunca está permitido','Cuando el vehículo de adelante va a virar a la izquierda, o en vías urbanas de 3 o más pistas en el mismo sentido','Solo a ciclistas'],r:2,exp:'La norma general prohíbe adelantar por la derecha. Las únicas excepciones son: 1) cuando el auto de adelante está realizando un giro a la izquierda. 2) en calles/avenidas urbanas (no autopistas) con 3 o más carriles en la misma dirección.'},
  {id:212,cat:'normas',q:'¿Cuál es el límite de velocidad en zonas rurales (carreteras de una pista por sentido) para vehículos livianos?',ops:['120 km/h','100 km/h','110 km/h','80 km/h'],r:1,exp:'En vías rurales (caminos de 1 pista por sentido) la máxima es 100 km/h. En autopistas (2 o más pistas por sentido, separadas por barrera) la máxima es 120 km/h para autos.'},
  {id:213,cat:'normas',q:'¿Cuál es la distancia mínima que un vehículo motorizado debe dejar al adelantar a un ciclista?',ops:['Medio metro','1 metro','1,5 metros como mínimo','No hay una distancia establecida por ley'],r:2,exp:'La Ley de Convivencia Vial (2018) establece que la distancia mínima de separación lateral al adelantar a un ciclista es de 1,5 metros, para evitar que la turbulencia del auto lo desestabilice.'},
  {id:214,cat:'normas',q:'En una vía urbana de dos pistas en el mismo sentido, usted va en la pista izquierda a 50 km/h y un vehículo lo sigue muy de cerca queriendo pasarlo. ¿Qué debe hacer?',ops:['Acelerar a 60 km/h para no estorbar','Frenar bruscamente para darle una lección','Ponerse a la derecha en cuanto sea seguro para dejarlo pasar libremente por la izquierda','Mantenerse en la pista izquierda ya que usted va a la velocidad máxima legal'],r:2,exp:'Usted nunca debe obstaculizar a otro vehículo que quiera sobrepasarlo (aunque el otro vaya sobre el límite de velocidad legal). Si la pista derecha está libre, póngase a la derecha y ceda el paso.'},
  {id:215,cat:'normas',q:'¿De qué depende principalmente el consumo de combustible de un vehículo?',ops:['De la marca del aceite del motor','Del estilo de conducción (aceleraciones bruscas, exceso de velocidad) y el mantenimiento del auto (presión neumáticos, filtros limpios)','De si llueve o hay sol','Solo del tamaño del motor, el conductor no influye'],r:1,exp:'La conducción eficiente (eco-driving) puede ahorrar hasta un 20% de bencina. Acelerar suavemente, pasar marchas a bajas revoluciones y mantener los neumáticos inflados reducen enormemente el consumo.'},

  // ===== SEÑALES =====
  {id:216,cat:'senales',q:'¿Qué indica una línea longitudinal BLANCA SEGMENTADA (entrecortada) en el centro de la calzada?',ops:['Prohibición de estacionar','Separa vías de sentido contrario y permite el adelantamiento con precaución','Zona de peatones','Camino solo para buses'],r:1,exp:'La línea central segmentada o discontinua indica que está PERMITIDO traspasarla para adelantar (a diferencia de la línea continua que lo prohíbe).'},
  {id:217,cat:'senales',q:'¿Qué color tienen las líneas que delimitan el borde de la calzada en una autopista (líneas de borde)?',ops:['Amarillas en ambos lados','Blancas en el lado derecho y blancas en el lado izquierdo','Blancas continuas en el borde derecho (berma) y amarillas continuas en el borde izquierdo (separador central)','Verdes'],r:2,exp:'Por convención en autopistas, la línea de la berma (borde derecho) es blanca, y la línea del bandejón central (borde izquierdo) es amarilla. Así el conductor sabe siempre cuál es el lado correcto, sobre todo de noche o con niebla.'},
  {id:218,cat:'senales',q:'Una tachuela (ojo de gato) reflectante de color ROJO en el centro de la calzada significa:',ops:['Peligro máximo, prohibido cruzar (generalmente acompaña a líneas continuas dobles o de borde izquierdo)','Precaución, se puede cruzar','Paso de cebra','Paradero de locomoción'],r:0,exp:'Los reflectantes (ojos de gato) en el centro de la calzada siguen un código de colores: Blanco (puedes pasar la pista), Amarillo (atención, línea continua), Rojo (prohibición total de traspaso o vía en contra).'},
  {id:219,cat:'senales',q:'¿Qué indica un semáforo con luz ROJA INTERMITENTE (parpadeando)?',ops:['Falla en el sistema, pasar con precaución','Tratarse exactamente igual que un CEDA EL PASO','Tratarse exactamente igual que una señal de PARE: detención obligatoria total, mirar a ambos lados y ceder paso a TODO vehículo o peatón antes de avanzar','No se puede avanzar por ningún motivo, esperar que cambie a verde'],r:2,exp:'Una luz roja intermitente equivale jurídicamente a una señal de PARE. Debe detener el vehículo por completo.'},
  {id:220,cat:'senales',q:'¿Qué indica un semáforo con luz AMARILLA INTERMITENTE?',ops:['Pare inmediatamente','Acelere para cruzar rápido antes que se ponga rojo','Indica precaución, actúe como si fuera un CEDA EL PASO, disminuyendo la velocidad al cruzar','Giro a la derecha obligatorio'],r:2,exp:'La luz amarilla parpadeante indica precaución al ingresar al cruce. Se asimila a una señal de Ceda el Paso.'},
  
  // ===== CONDUCCION 2 =====
  {id:221,cat:'manejo',q:'Al enfrentarse a un charco de agua profundo y extenso, ¿qué debe hacer?',ops:['Acelerar para cruzar rápido','Pasar por el medio donde está más profundo','Poner la marcha más corta (1ra), acelerar de forma constante y sostenida para que no entre agua por el escape de gases, pero a velocidad moderada','Frenar bruscamente en el agua'],r:2,exp:'Al vadear agua profunda, debe usar primera marcha para mantener altas revoluciones en el motor (evitando que el agua entre por la succión del tubo de escape) pero ir lento para no mojar los componentes eléctricos (distribuidor/bujías).'},
  {id:222,cat:'manejo',q:'¿Qué sucede si frena fuertemente un vehículo que NO tiene frenos ABS en un piso resbaladizo?',ops:['El vehículo frena el doble de rápido','Las ruedas se bloquean, el vehículo patinará y usted perderá totalmente el control de la dirección del volante','Los neumáticos se secan rápido por la fricción','No sucede nada diferente'],r:1,exp:'Sin ABS, una frenada de pánico bloquea los neumáticos ("ruedas chantadas"). Un neumático que no gira no tiene dirección, por lo que el auto seguirá recto sin importar hacia dónde gire usted el volante.'},
  {id:223,cat:'manejo',q:'¿Cómo funciona el freno ABS (Sistema Antibloqueo)?',ops:['Acorta siempre la distancia de frenado un 50%','Bombea y suelta los frenos automáticamente decenas de veces por segundo para evitar que la rueda se bloquee, permitiendo al conductor mantener el control del volante (esquivar obstáculos) mientras frena a fondo','Impide que el auto vuelque','Enfría los frenos con agua de la lluvia'],r:1,exp:'La gran ventaja del ABS NO es acortar la distancia, sino EVITAR el bloqueo. Al mantener las ruedas girando ligerísimamente mientras frenan fuerte, permite que el auto siga la trayectoria que usted le marca con el volante (poder esquivar el choque).'},
  {id:224,cat:'manejo',q:'¿Qué debe hacer si empieza a sentir sueño intenso ("pesadez en los ojos") conduciendo en carretera?',ops:['Abrir la ventana, poner música alta y tomar agua fría para resistir','Acelerar para llegar más pronto a su destino','Detenerse lo antes posible en un lugar seguro (estación de servicio, berma ancha), dormir una siesta de 15-20 minutos, y si es necesario tomar un café u otra bebida estimulante antes de reanudar el viaje','Cerrar un ojo para descansar mientras se conduce con el otro'],r:2,exp:'Abrir ventanas, poner música o comer NO curan el sueño, solo lo postergan un par de minutos, provocando microsueños fatales. La única cura es DORMIR o cambiar de conductor.'},
  {id:225,cat:'manejo',q:'Al aproximarse de noche por detrás a un ciclista que no tiene luces encendidas, el peligro es:',ops:['Ser multado por carabineros','Que no podamos detectar su presencia a tiempo para reaccionar a una distancia segura, provocando una colisión por alcance','Que su bicicleta pinche','Que el ciclista vaya muy rápido'],r:1,exp:'Un ciclista de noche y sin ropa reflectante ni luces es invisible a más de 20 metros. Cuando lo veamos con las luces bajas del auto ya no habrá tiempo de frenar (un auto a 50 km/h necesita 27 metros).'},
  
  // ===== MECÁNICA 2 =====
  {id:226,cat:'mecanica',q:'¿Qué indica que un neumático necesita alineación o balanceo?',ops:['Si al conducir en recta el volante tiende a irse hacia un lado, o vibra a cierta velocidad','Si el auto consume menos bencina','Si frena muy rápido','Si suena el tubo de escape'],r:0,exp:'Si el auto "tira" hacia un lado al soltar levemente el volante en recta, necesita ALINEACIÓN de la dirección. Si el volante vibra entre los 80 y 100 km/h, suele necesitar BALANCEO de los pesos de las ruedas.'},
  {id:227,cat:'mecanica',q:'¿Dónde encuentra las indicaciones exactas sobre la presión que deben llevar los neumáticos de su vehículo?',ops:['Escritas en el flanco del neumático','En el manual del propietario del vehículo, o en un adhesivo ubicado comúnmente en el marco de la puerta del conductor o tapa de bencina','Preguntándole al bombero en la estación de servicio','En una tabla de internet general'],r:1,exp:'La presión correcta la determina el FABRICANTE DEL AUTO, no el del neumático. Está en el manual o en un sticker en la puerta. (Lo que dice el neumático al costado es la presión máxima que soporta antes de reventar, NO la recomendada para el auto).'},
  {id:228,cat:'mecanica',q:'¿Qué pieza clave evita que su vehículo contamine excesivamente?',ops:['El radiador','El convertidor catalítico (ubicado en el tubo de escape) que transforma gases tóxicos en gases inocuos (como vapor de agua y CO2)','El motor de arranque','El filtro de aceite'],r:1,exp:'El convertidor catalítico, presente en todos los autos inyectados modernos, utiliza metales preciosos en su interior que reaccionan con los gases de escape tóxicos quemándolos antes de que salgan a la atmósfera.'},
  {id:229,cat:'mecanica',q:'¿Cuándo el vehículo emite humo azul de forma continua por el tubo de escape, es síntoma de:',ops:['Que el motor está muy frío (condensación normal)','Problema en la inyección (quemando mucha bencina)','Problema de compresión/desgaste interno grave: el motor está quemando el aceite lubricante junto con el combustible','Que la batería está dañada'],r:2,exp:'*Humo Blanco= vapor condensación (normal en frío) o agua en cilindros (empaquetadura culata). *Humo Negro= exceso de combustible inyectado (mezcla rica). *Humo Azul= Motor está quemando el aceite interno. Requiere reparación mayor urgente.'},
  {id:230,cat:'mecanica',q:'¿Para qué sirven los fusibles en el sistema eléctrico de un auto?',ops:['Proporcionan la energía inicial','Protegen el sistema: se queman o "cortan" intencionalmente si hay un cortocircuito o una subida brusca de amperaje, evitando incendios eléctricos','Aumentan el voltaje para la radio','Para saber cuándo cambiar el aceite'],r:1,exp:'Los fusibles son mecanismos de sacrificio. Tienen un filamento de un grosor calculado que se funde si pasa demasiada corriente. Si la radio o luces dejan de funcionar repentinamente, lo primero a revisar es la caja de fusibles.'}
];

let content = fs.readFileSync('preguntas.js', 'utf8');
let nuevasLineas = '';
nuevas.forEach(p => {
  const ops = JSON.stringify(p.ops);
  nuevasLineas += '  { id:' + p.id + ', categoria:"' + p.cat + '", pregunta:"' + p.q + '", opciones:' + ops + ', respuesta:' + p.r + ', explicacion:"' + p.exp + '" },\n';
});
content = content.replace('];\n\nconst CATEGORIAS', nuevasLineas + '];\n\nconst CATEGORIAS');
fs.writeFileSync('preguntas.js', content, 'utf8');

let html = fs.readFileSync('index.html', 'utf8');
html = html.replace('210 preguntas', '230 preguntas');
fs.writeFileSync('index.html', html, 'utf8');

console.log('Agregadas ' + nuevas.length + ' preguntas.');
