const fs = require('fs');

const nuevas = [
  // ===== EL INDIVIDUO EN EL TRÁNSITO / CANSANCIO Y SUEÑO =====
  {id:251,cat:'seguridad',q:'¿En qué horario ocurren la mayoría de los accidentes de tránsito causados por el sueño en Chile?',ops:['Entre las 12:00 y las 14:00 horas','Entre las 02:00 y las 06:00 de la madrugada, y entre las 14:00 y las 16:00 horas','Solamente al amanecer','Solamente durante el atardecer'],r:1,exp:'Según CONASET, los ritmos biológicos humanos (ritmo circadiano) producen una fuerte somnolencia natural entre las 2 y 6 de la madrugada, y una leve baja después de almuerzo (2 a 4 PM).'},
  {id:252,cat:'seguridad',q:'¿Cuál es el primer síntoma de fatiga o cansancio al volante?',ops:['Quedarse dormido profundamente','Cerrar los ojos involuntariamente','La falta de interés en el entorno, bostezos continuos y dificultad para mantener la concentración o recordar los últimos kilómetros recorridos','El dolor de espalda'],r:2,exp:'Mucho antes de que los ojos se cierren, el cerebro ya está fatigado: el conductor se distrae fácilmente, le cuesta mantener la posición en la pista y hace correcciones bruscas al volante.'},
  {id:253,cat:'seguridad',q:'Usted va conduciendo y siente que está resfriado, por lo que tomó un jarabe que contiene codeína. ¿Qué riesgo principal corre?',ops:['Que la codeína acelera sus reflejos y puede chocar por frenar antes','Que le provocará un fuerte dolor de cabeza','Que la codeína produce mucha somnolencia, disminuyendo los reflejos y la atención','Ninguno, porque es un remedio recetado'],r:2,exp:'La codeína (presente en analgésicos fuertes y jarabes para la tos) es un depresor del sistema nervioso, muy similar a una droga, produciendo alta somnolencia e incapacidad de concentrarse.'},
  {id:254,cat:'seguridad',q:'¿Cómo afecta el alcohol a la visión del conductor?',ops:['Mejora la visión de noche','Disminuye el campo visual (visión de túnel) e impide calcular correctamente las distancias','Aumenta el campo visual periférico','No afecta a la visión, solo al equilibrio'],r:1,exp:'El alcohol reduce la capacidad del cerebro para procesar los bordes de la visión, creando "visión de túnel". El conductor ya no se percata de peatones u objetos que vienen por los costados.'},
  {id:255,cat:'seguridad',q:'Según el Libro del Nuevo Conductor, ¿cuánto tiempo tarda en promedio el hígado humano en eliminar 1 gramo de alcohol por litro de sangre?',ops:['Cerca de 1 hora','Cerca de 10 horas','Aproximadamente 4 horas','Un par de minutos si se toma café'],r:1,exp:'El cuerpo metaboliza el alcohol lentamente a una tasa de 0,10 a 0,15 gramos por hora. Eliminar 1 gramo puede tardar unas 10 horas. Ni dormir, ni duchas frías ni café aceleran este proceso orgánico.'},

  // ===== VELOCIDAD Y FÍSICA =====
  {id:256,cat:'manejo',q:'¿Qué es la "Distancia de Reacción"?',ops:['La distancia que recorre el vehículo mientras se pisa el pedal de freno','La distancia total desde que se ve el peligro hasta que el vehículo se detiene por completo','La distancia que recorre el vehículo desde que el conductor ve el peligro hasta que pisa el pedal del freno','La distancia que recorre el auto al chocar'],r:2,exp:'La distancia de reacción es el trayecto recorrido durante el "Tiempo de Reacción" (promedio 1 segundo). Si va a 90 km/h, en ese segundo recorre 25 metros ANTES de empezar a frenar.'},
  {id:257,cat:'manejo',q:'¿Cómo se calcula aproximadamente la Distancia de Reacción de un conductor normal en 1 segundo?',ops:['Multiplicando la primera cifra de la velocidad por 3 (Ej: a 70 km/h -> 7x3=21 metros)','Multiplicando la velocidad por 5','Dividiendo la velocidad a la mitad','Multiplicando por 2'],r:0,exp:'Fórmula rápida: se toma la primera cifra de la velocidad y se multiplica por 3. A 60 km/h -> 6 x 3 = 18 metros. A 90 km/h -> 9 x 3 = 27 metros recorridos antes de frenar.'},
  {id:258,cat:'manejo',q:'¿Cómo afecta la velocidad a la Energía Cinética de un vehículo?',ops:['Si la velocidad se duplica, la energía también se duplica','Si la velocidad se duplica, la energía cinética aumenta al CUADRADO (4 veces más)','Si la velocidad aumenta, la energía disminuye','La energía cinética solo depende del peso, no de la velocidad'],r:1,exp:'La física dictamina que E = 1/2 * m * v^2. Si usted duplica la velocidad (de 30 a 60), su energía y la distancia de frenado se multiplican por 4. Si la triplica, se multiplica por 9.'},
  {id:259,cat:'manejo',q:'Al aumentar la velocidad de 40 km/h a 80 km/h, ¿qué pasa con la Distancia de Frenado?',ops:['Se duplica','Se reduce a la mitad','Aumenta 4 veces','Se mantiene igual'],r:2,exp:'Como se duplicó la velocidad (x2), la distancia de frenado aumenta al cuadrado (2x2 = 4). Necesitará 4 veces más metros para detener el auto físicamente.'},
  {id:260,cat:'manejo',q:'¿Qué es la fuerza centrífuga en una curva?',ops:['La fuerza que empuja el vehículo hacia el interior de la curva','La fuerza física que tiende a sacar al vehículo de su trayectoria en la curva, empujándolo hacia el exterior','La fuerza del viento','La fuerza de frenado del motor'],r:1,exp:'La inercia (fuerza centrífuga) hace que el vehículo quiera seguir en línea recta. Si entra muy rápido a la curva, la adherencia de las ruedas será vencida y el auto saldrá despedido hacia afuera.'},

  // ===== USUARIOS VULNERABLES (PEATONES, CICLISTAS, NIÑOS) =====
  {id:261,cat:'normas',q:'¿Por qué los niños pequeños corren mayor riesgo de ser atropellados?',ops:['Porque caminan muy lento','Porque su baja estatura impide que sean vistos detrás de autos estacionados y su campo visual está menos desarrollado (no evalúan bien las distancias y velocidades de los autos)','Porque siempre van en bicicleta','Porque no saben hablar'],r:1,exp:'El campo visual de un niño es más estrecho. Su cerebro aún no puede juzgar a qué velocidad se acerca un auto. Además, reaccionan impulsivamente corriendo detrás de una pelota.'},
  {id:262,cat:'normas',q:'Al acercarse a un furgón escolar detenido con sus luces destellantes (baliza) encendidas, usted debe:',ops:['Tocar la bocina para que los niños se apresuren','Acelerar para pasarlo rápido','Reducir la velocidad y estar preparado para detenerse, ya que hay niños subiendo o bajando que pueden cruzar la calle inesperadamente','Adelantarlo por la vereda'],r:2,exp:'La baliza amarilla (o en las esquinas superiores) del transporte escolar indica subida/bajada de escolares. El conductor debe prever que un niño podría cruzar la calle por delante o por detrás del furgón.'},
  {id:263,cat:'normas',q:'Usted se acerca a un paso de cebra y ve a una persona mayor usando un bastón blanco. ¿Qué significa?',ops:['Que es una persona sorda','Que es una persona ciega (o con discapacidad visual severa) y usted debe extremar la precaución y darle tiempo adicional para cruzar','Que es una persona mayor sana','Que usted tiene preferencia'],r:1,exp:'El bastón blanco es el símbolo universal de la ceguera. Un bastón blanco con rojo indica sordera-ceguera. Siempre se les debe dar prioridad total y tiempo extra.'},
  {id:264,cat:'normas',q:'Un grupo de ciclistas va transitando por la calzada. ¿Cómo deben hacerlo según la ley?',ops:['En un pelotón ocupando ambas pistas','Deben circular por la ciclovía si existe, de lo contrario por el lado derecho de la calzada, en fila india (uno detrás del otro)','Por la vereda esquivando peatones','En sentido contrario al tránsito'],r:1,exp:'Los ciclistas son vehículos. Tienen prohibida la vereda (salvo menores de 14 y adultos mayores) y si no hay ciclovía, deben ir por el costado derecho de la calle, en hilera (no en paralelo).'},
  {id:265,cat:'normas',q:'Si un peatón baja a la calzada para esquivar un obstáculo en la vereda (ej: una obra o charco), ¿quién tiene prioridad?',ops:['El automóvil, el peatón debió esperar','El peatón tiene la prioridad; los vehículos deben detenerse o disminuir la marcha para permitirle rodear el obstáculo de forma segura','La municipalidad','Los ciclistas'],r:1,exp:'La normativa indica que, frente a trabajos en la acera que obliguen al peatón a usar parte de la calzada, este último siempre tiene la preferencia.'},

  // ===== SEÑALIZACIÓN Y DEMARCACIONES =====
  {id:266,cat:'senales',q:'¿Qué significa una línea longitudinal AMARILLA CONTINUA en el centro de la vía?',ops:['Que puede adelantar si es seguro','Que es un camino privado','Que divide flujos vehiculares de sentidos opuestos y prohíbe absolutamente el adelantamiento o traspaso de dicha línea','Zona de estacionamiento'],r:2,exp:'El color amarillo en líneas centrales siempre advierte tráfico en contra. Que sea continua (sin cortes) significa prohibición legal y física de traspasarla (por ej: curva ciega o cima de cuesta).'},
  {id:267,cat:'senales',q:'Una señal de tránsito en forma de ROMBO y color AMARILLO con letras negras indica:',ops:['Dirección obligatoria','Velocidad máxima','Es una señal PREVENTIVA (advierte un peligro próximo como una curva, zona escolar o puente angosto)','Turismo'],r:2,exp:'Las señales preventivas o de advertencia de peligro tienen forma de rombo amarillo (diamante). Te avisan de riesgos que aún no ves para que bajes la velocidad con tiempo.'},
  {id:268,cat:'senales',q:'¿Qué indican las señales de tránsito de color VERDE y rectangulares?',ops:['Prohibición de estacionar','Peligros en la vía','Son señales INFORMATIVAS (indican distancias a ciudades, rutas, direcciones y nombres de calles)','Zonas de obras'],r:2,exp:'Las señales informativas de orientación generalmente son verdes o azules. Guían al conductor indicando el destino, kilómetros faltantes y empalmes viales.'},
  {id:269,cat:'senales',q:'¿Qué debe hacer si el semáforo cambia de verde a amarillo justo cuando usted está ingresando o ya dentro del cruce?',ops:['Frenar violentamente dentro de la intersección','Retroceder rápidamente','Continuar su marcha y despejar la intersección con precaución','Tocar la bocina y estacionar'],r:2,exp:'Si el amarillo te sorprende tan cerca de la línea de detención que frenar bruscamente causaría un choque por alcance, o si ya pisaste el cruce, DEBES terminar de cruzar y despejar la vía.'},
  {id:270,cat:'senales',q:'¿Qué indica un semáforo con una FLECHA ROJA?',ops:['Que debe avanzar con precaución en esa dirección','Que el viraje en la dirección de la flecha está prohibido, aunque la luz principal esté en verde','Que es obligatorio doblar','Que está en pana'],r:1,exp:'La flecha roja prohíbe estrictamente virar en esa dirección. Por ejemplo, la calle de frente puede estar verde, pero no puedes girar a la derecha hasta que la flecha cambie a verde.'},

  // ===== CONDUCCIÓN Y MEDIO AMBIENTE =====
  {id:271,cat:'mecanica',q:'¿Por qué NO es recomendable "calentar el motor" con el vehículo detenido por muchos minutos?',ops:['Porque gasta batería','Porque el motor de inyección moderno no lo necesita; gasta combustible inútilmente y contamina. Se debe arrancar e iniciar la marcha lentamente','Porque el motor se enfría','Porque desgasta los frenos'],r:1,exp:'Calentar el motor en ralentí (parado) es un mito de los autos antiguos a carburador. Los autos actuales deben ser conducidos de inmediato pero sin acelerones bruscos los primeros 5 minutos.'},
  {id:272,cat:'mecanica',q:'¿Qué efecto tiene llevar el equipaje en una parrilla sobre el techo en vez de en el maletero?',ops:['Disminuye el consumo de bencina por el peso arriba','Aumenta enormemente la resistencia aerodinámica, lo que eleva el consumo de combustible hasta en un 20%','Mejora la estabilidad del vehículo en curvas','No tiene ningún efecto'],r:1,exp:'El equipaje en el techo (incluso las cúpulas aerodinámicas vacías) frena el vehículo por el roce del viento. Para mantener la velocidad, el conductor debe pisar más el acelerador, gastando mucho más.'},
  {id:273,cat:'mecanica',q:'¿Cuándo se debe usar el aire acondicionado (A/C) para ser más eficiente en carretera?',ops:['Nunca en carretera','En carretera a altas velocidades (más de 80 km/h) es más eficiente usar A/C que llevar las ventanas abajo, ya que las ventanas abiertas rompen la aerodinámica y gastan más bencina que el compresor del A/C','Es mejor llevar las ventanas siempre abiertas a 120 km/h','El A/C no gasta bencina'],r:1,exp:'A bajas velocidades (ciudad), abrir ventanas gasta menos. Pero en autopistas, el freno aerodinámico de las ventanas abiertas consume mucha más energía que mantener los vidrios arriba y usar el A/C.'},
  {id:274,cat:'mecanica',q:'¿Qué gas letal e inodoro produce un vehículo de combustión interna, que hace peligroso encenderlo dentro de un garaje cerrado?',ops:['Oxígeno puro','Vapor de agua (H2O)','Monóxido de carbono (CO)','Dióxido de azufre'],r:2,exp:'El monóxido de carbono (CO) no tiene olor ni color, pero es altamente venenoso. En un garaje cerrado, inhalarlo causa dolor de cabeza, mareos, desmayos y la muerte por asfixia en minutos.'},

  // ===== EMERGENCIAS Y FALLAS =====
  {id:275,cat:'seguridad',q:'Usted va conduciendo y sorpresivamente se le revienta un neumático trasero. ¿Qué hará el vehículo?',ops:['Se levantará de la parte delantera','Frenará de inmediato solo','La parte trasera del vehículo comenzará a patinar (colear) violentamente de un lado a otro','Seguirá derecho sin problemas'],r:2,exp:'Un reventón trasero provoca "sobreviraje" (coleo). El conductor debe girar el volante suavemente hacia el lado que patina la cola para enderezarlo, NO frenar bruscamente.'},
  {id:276,cat:'seguridad',q:'Si los frenos fallan completamente (el pedal se va a fondo sin resistencia), la primera acción del conductor debe ser:',ops:['Saltar del vehículo','Bombear fuertemente el pedal del freno varias veces seguidas para intentar recuperar la presión del sistema hidráulico','Tirar el freno de mano de golpe al máximo','Girar la llave y apagar el motor'],r:1,exp:'La pérdida total suele ser por bajo nivel de líquido o vapor (fading). Bombear rápido el pedal puede comprimir el aire/líquido remanente y recuperar algo de freno. Además, debe bajar las marchas (freno de motor).'},
  {id:277,cat:'seguridad',q:'¿Para qué sirven las "luces de estacionamiento" (luces de posición o gálibo)?',ops:['Para iluminar la carretera de noche','Para usarlas de día como luces principales','Solo para indicar la presencia y anchura del vehículo cuando está estacionado en zonas oscuras o de baja visibilidad (como niebla), NUNCA para circular','Para encandilar'],r:2,exp:'Las luces de posición (el primer click de las luces, que no iluminan el camino) solo marcan la silueta del auto. Está prohibido circular de noche solo con esas luces (se deben usar luces bajas).'},
  {id:278,cat:'seguridad',q:'Si un conductor padece epilepsia, ¿puede obtener su licencia de conducir en Chile?',ops:['Sí, en cualquier momento','Solo si presenta un certificado de su médico tratante que acredite que la enfermedad está controlada y no presenta crisis (estado asintomático bajo tratamiento)','No, la ley lo prohíbe absolutamente para siempre','Sí, sin ningún requisito especial'],r:1,exp:'Enfermedades crónicas como diabetes, hipertensión grave o epilepsia requieren evaluación médica estricta y certificados de estar bajo control médico para que el gabinete psicosensométrico lo apruebe.'},
  
  // ===== TÉCNICAS DE MANEJO SEGURO =====
  {id:279,cat:'manejo',q:'Al aproximarse a la cima de una cuesta (una subida pronunciada sin ver el otro lado), usted debe:',ops:['Acelerar y adelantar a los vehículos lentos','Tocar la bocina y subir con luces altas','Reducir la velocidad y mantenerse estrictamente a la derecha, ya que su campo visual es nulo y puede venir un vehículo adelantando en sentido contrario','Frenar y detenerse en la cima'],r:2,exp:'Las cimas son puntos ciegos críticos (cambios de rasante). Nunca se debe adelantar ni ir rápido, porque no sabemos si detrás del montículo hay un auto cruzado, un camión o un accidente.'},
  {id:280,cat:'manejo',q:'¿Qué regla práctica se recomienda para mantener una "distancia de seguimiento segura" en carretera con pavimento seco?',ops:['La regla del medio metro','La regla de los 3 segundos (dejar pasar 3 segundos desde que el auto de adelante pasa una marca, hasta que usted pasa la misma)','La regla de no verle la patente al de adelante','La regla de los 10 segundos'],r:1,exp:'La "Regla de los 3 segundos" asegura que, independiente de la velocidad, usted siempre tendrá la distancia (en metros) de reacción + frenado suficiente para detenerse si el otro frena de emergencia.'},
  {id:281,cat:'manejo',q:'Si usted conduce a 100 km/h bajo la lluvia, ¿cuántos segundos de distancia de seguimiento debería mantener?',ops:['3 segundos','Al menos 6 segundos (se debe duplicar la distancia que usaría en pavimento seco)','1 segundo','No importa el tiempo'],r:1,exp:'Si en seco son 3 segundos, con lluvia/niebla/pavimento mojado la adherencia se reduce a la mitad. Por lo tanto, el margen de seguridad debe duplicarse a 6 segundos.'},
  {id:282,cat:'manejo',q:'¿Por qué los adelantamientos en carretera de una vía (doble sentido) son la maniobra más riesgosa?',ops:['Porque gastan mucha gasolina','Porque requieren calcular perfectamente la velocidad del vehículo a adelantar, nuestra aceleración, y la distancia y velocidad del vehículo que viene en contra (choque frontal)','Porque hay que usar la bocina','Porque hay que cambiar de radio'],r:1,exp:'El cálculo visual humano es muy malo estimando la velocidad de un auto que viene de frente. Un choque frontal a 100 km/h equivale a chocar contra un muro a 200 km/h.'},
  {id:283,cat:'manejo',q:'Antes de iniciar un adelantamiento, usted observa que el vehículo detrás suyo encendió su intermitente izquierdo y empezó a salir a la pista contraria. ¿Qué debe hacer usted?',ops:['Acelerar rápido y salir primero a la pista contraria para ganarle','Encender su intermitente para decirle que usted va primero','Desistir de su maniobra, mantenerse en su pista y dejar que el vehículo de atrás termine de adelantarlo a usted','Frenar bruscamente'],r:2,exp:'El conductor que ya inició la maniobra (el de atrás que ya salió) tiene la preferencia temporal. Usted debe abortar su intención y esperar.'},
  {id:284,cat:'manejo',q:'Mientras usted está adelantando a un camión largo en carretera, siente fuertes ráfagas de viento. ¿Qué peligro hay?',ops:['Que se le apaguen las luces','El camión hace de "barrera" contra el viento. Al terminar de pasarlo, usted perderá esa protección y el viento lateral golpeará su auto empujándolo hacia la cuneta o hacia el camión','Que el camión frene','Ninguno, el viento ayuda'],r:1,exp:'El vacío aerodinámico y la repentina ráfaga de viento de costado al salir del "abrigo" del camión, desestabilizan los autos ligeros. Se debe sujetar fuerte el volante.'},

  // ===== CONVIVENCIA VIAL Y ESTACIONAMIENTO =====
  {id:285,cat:'normas',q:'¿En qué sentido (dirección) es obligatorio estacionar un vehículo en una calle de un solo sentido?',ops:['En sentido contrario al tránsito para salir rápido','En cualquiera de los dos','De forma paralela a la cuneta (borde), en el MISMO SENTIDO del tránsito y a no más de 30 cm de la vereda','En diagonal siempre'],r:2,exp:'La Ley indica que el estacionamiento debe ser paralelo a la cuneta, a máximo 30 cm de distancia, y las ruedas y el auto deben apuntar en la misma dirección que el flujo vehicular.'},
  {id:286,cat:'normas',q:'Al estacionar en una pendiente o bajada pronunciada, ¿hacia dónde debe dejar giradas las ruedas delanteras?',ops:['Hacia el centro de la calle','Hacia el borde o cuneta (acera), de modo que si los frenos fallan el vehículo choque de inmediato con la cuneta y no baje por la calle','Rectas','Da lo mismo'],r:1,exp:'Como medida extra de seguridad al freno de mano y dejar enganchado en Retroceso, girar las ruedas hacia la acera crea un tope físico natural.'},
  {id:287,cat:'normas',q:'¿Puede usted estacionar su vehículo sobre la vereda (acera)?',ops:['Sí, si no obstaculiza a los peatones','Solo en zonas residenciales','No, la Ley prohíbe absolutamente detenerse o estacionarse sobre las aceras, pasos de cebra y cruces peatonales','Sí, si paga parquímetro'],r:2,exp:'Las veredas son de uso exclusivo peatonal. Detener un vehículo (aunque sea por 2 minutos con intermitentes) sobre la vereda, platabandas o ciclovías está prohibido y es fiscalizado.'},
  {id:288,cat:'normas',q:'¿Cuándo debe usar usted la bocina del vehículo?',ops:['Para apurar al conductor de adelante en un semáforo','Para saludar a un conocido en la calle','Única y exclusivamente para prevenir o advertir un accidente inminente (ej: alguien va a retroceder contra su auto sin verlo)','Para llamar a alguien desde la casa'],r:2,exp:'El uso de aparatos sonoros está prohibido, excepto para prevenir un siniestro inminente. El ruido afecta la convivencia vial y aísla auditivamente a peatones y ciclistas.'},
  {id:289,cat:'normas',q:'En relación con los "Puntos Ciegos" o "Ángulos Muertos" de los espejos de su auto, es CORRECTO afirmar que:',ops:['Son zonas que no existen en los autos modernos','Se pueden eliminar por completo con los espejos laterales','Siempre quedará un área a los lados del vehículo que no se ve por ningún espejo, por lo que antes de cambiar de pista se debe girar brevemente la cabeza por sobre el hombro','Solo afectan a los camiones grandes'],r:2,exp:'A pesar de ajustar los espejos, existe un espacio lateral (punto ciego) donde cabe una moto o un auto completo. Antes de cambiar de carril, es vital mirar rápidamente por sobre el hombro (visión directa).'},
  
  // ===== LEYES Y LICENCIAS =====
  {id:290,cat:'normas',q:'Si un conductor joven de 17 años obtiene su licencia Clase B, ¿puede conducir solo?',ops:['Sí, es igual que cualquier licencia','No, la Ley exige que los jóvenes de 17 años conduzcan OBLIGATORIAMENTE acompañados en el asiento delantero por un conductor que posea Licencia Clase B (o superior) con al menos 5 años de antigüedad','Sí, pero solo de día','No, no pueden obtener licencia en Chile'],r:1,exp:'Excepcionalmente se otorga licencia a los 17 (previa escuela de conductores), pero con la limitante de ir bajo tutela de un adulto con licencia madura, hasta que el joven cumpla los 18.'},
  {id:291,cat:'normas',q:'¿Qué sanción recibe un conductor si es sorprendido manejando con la licencia suspendida o cancelada?',ops:['Paga una multa menor','No le pasa nada si no chocó','Es detenido por Carabineros y el vehículo puede ser retirado de circulación, considerándose una infracción gravísima con posible denuncia judicial','Debe renovarla ese mismo día'],r:2,exp:'Conducir sin licencia (o con licencia retenida por un juez) invalida cualquier seguro. Es un delito y una falta gravísima, exponiéndose al decomiso del vehículo y multas altísimas.'},
  {id:292,cat:'normas',q:'Según la normativa chilena, ¿está permitido usar audífonos para escuchar música (o manos libres en ambos oídos) mientras se conduce?',ops:['Sí, porque aísla del ruido de las bocinas','Sí, siempre que la música sea suave','No, está prohibido llevar auriculares conectados a reproductores de sonido en ambos oídos porque aíslan al conductor del entorno auditivo (sirenas, frenadas)','Solo se permiten en la autopista'],r:2,exp:'El sentido de la audición es tan vital como la vista para reaccionar ante una emergencia. Los audífonos intraurales o de diadema suprimen los sonidos externos como sirenas de bomberos.'},
  {id:293,cat:'normas',q:'Si usted compra un vehículo usado, ¿qué debe hacer para que el seguro obligatorio (SOAP) sea válido?',ops:['Nada, el seguro es automático','El seguro debe transferirse o adquirirse a nombre del nuevo propietario; debe siempre coincidir la patente y los datos del padrón vehicular','Comprar un seguro de hogar','Pegar un sticker en el vidrio'],r:1,exp:'El SOAP cubre accidentes personales del vehículo (patente). Al transferir, se debe asegurar que el SOAP vigente quede asociado correctamente y portar el documento impreso o digital en el auto.'},
  
  // ===== MECÁNICA EXTRA =====
  {id:294,cat:'mecanica',q:'¿Cuál es la función del "Motor de Arranque" (burro de arranque)?',ops:['Generar la electricidad para las luces','Dar el movimiento rotatorio inicial al motor a combustión utilizando la energía de la batería, para que este encienda y empiece a funcionar por sí solo','Mantener el ralentí','Enfriar el radiador'],r:1,exp:'Un motor de gasolina/diésel necesita estar girando para aspirar aire y chispas. El pequeño motor de arranque eléctrico lo hace girar esos primeros segundos hasta que "arranca".'},
  {id:295,cat:'mecanica',q:'Si el pedal de embrague de su vehículo está muy "duro" o cuesta pasar los cambios (marchas raspan), indica que:',ops:['Las ruedas están desinfladas','El sistema de transmisión (disco, prensa o piola del embrague) está desgastado o defectuoso y requiere reparación mecánica','La batería está sin carga','El filtro de aire está sucio'],r:1,exp:'El roce (rasposo) al engranar marchas o dureza del pedal son síntomas clásicos de un embrague fatigado que ya no desacopla completamente el motor de la caja de cambios.'},
  {id:296,cat:'mecanica',q:'¿Qué mantenimiento periódico exigen las bujías en los motores de gasolina?',ops:['Deben cambiarse cada día','No tienen mantenimiento','Deben ser inspeccionadas y cambiadas periódicamente (ej: cada 30.000 a 60.000 km) porque su electrodo se desgasta, causando fallas de encendido y alto consumo','Solo se limpian con agua'],r:2,exp:'Las bujías generan la chispa que explota la gasolina. Con el kilometraje se funden. Unas bujías malas hacen que el auto tiritee, pierda fuerza y rinda menos kilómetros por litro.'},
  {id:297,cat:'mecanica',q:'¿Por qué se deben cruzar (rotar) los neumáticos de un vehículo cada ciertos kilómetros (ej: cada 10.000 km)?',ops:['Para limpiarlos','Para igualar el nivel de desgaste de los neumáticos delanteros (que sufren el peso del motor y giran) con los traseros, prolongando la vida útil del juego completo','Para cambiarles el aire','Para no aburrirse de ver la misma rueda'],r:1,exp:'Los neumáticos delanteros de un auto (generalmente de tracción delantera) se gastan el doble de rápido que los traseros porque frenan, traccionan y giran la dirección. Rotarlos equilibra su desgaste.'},
  
  // ===== MISC =====
  {id:298,cat:'seguridad',q:'Usted desciende de su vehículo en plena autopista por una emergencia (pinchazo). ¿Cómo debe actuar?',ops:['Quedarse en medio de la pista pidiendo ayuda','Ponerse el chaleco reflectante amarillo ANTES de bajarse del auto, instalar los triángulos de emergencia (a unos 50-100m atrás) y esperar detrás de las barreras de contención (seguridad)','Salir a correr por la berma','Empezar a cambiar la rueda sin mirar el tránsito'],r:1,exp:'En autopista, ser atropellado en la berma es letal. Se exige máxima visibilidad (chaleco) y alertar lejos (triángulos). Luego refugiarse a un costado fuera del asfalto mientras llega la grúa.'},
  {id:299,cat:'manejo',q:'¿Qué es el "punto de fricción" al sacar el embrague?',ops:['Cuando las ruedas patinan en el barro','El momento exacto en el recorrido del pedal donde el motor comienza a transmitir fuerza a las ruedas (el auto vibra levemente y quiere avanzar). Es fundamental para dominar la salida en subida','Cuando los frenos se recalientan','Cuando el volante está duro'],r:1,exp:'Dominar el "punto de fricción" o "punto de acople" es la habilidad básica en autos manuales para salir suavemente sin que el motor se detenga (se cale), especialmente al partir en pendientes.'},
  {id:300,cat:'normas',q:'¿Cuántos metros antes de virar (doblar) en una esquina debe usted señalizar obligatoriamente con los intermitentes?',ops:['5 metros antes','Al menos 10 metros antes','Al menos 30 metros antes de iniciar la maniobra de viraje (o cambio de pista)','No es obligatorio en la ciudad'],r:2,exp:'La Ley de Tránsito en Chile especifica expresamente que la intención de virar o cambiar de pista debe señalizarse mediante los intermitentes luminosos con una anticipación MÍNIMA de 30 metros.'}
];

let content = fs.readFileSync('preguntas.js', 'utf8');

let nuevasLineas = '';
nuevas.forEach(p => {
  nuevasLineas += '  { id:' + p.id + ', categoria:\'' + p.cat + '\', pregunta:\'' + p.q.replace(/'/g, "\\'") + '\', opciones:[' + p.ops.map(o => `'${o.replace(/'/g, "\\'")}'`).join(',') + '], respuesta:' + p.r + ', explicacion:\'' + p.exp.replace(/'/g, "\\'") + '\' },\n';
});

content = content.replace('];\n\nconst CATEGORIAS', nuevasLineas + '];\n\nconst CATEGORIAS');
fs.writeFileSync('preguntas.js', content, 'utf8');

let html = fs.readFileSync('index.html', 'utf8');
html = html.replace('250 preguntas', '300 preguntas');
html = html.replace('250 preguntas', '300 preguntas'); // fallback
fs.writeFileSync('index.html', html, 'utf8');

console.log('Agregadas ' + nuevas.length + ' preguntas.');
