const fs = require('fs');

const nuevas = [
  // ===== MECANICA =====
  {id:171,cat:'mecanica',q:'¿Qué función cumple la batería en el vehículo?',ops:['Producir la energía mecánica para mover las ruedas','Almacenar energía química para transformarla en eléctrica y encender el motor','Enfriar el motor','Generar chispas constantemente mientras el vehículo se mueve'],r:1,exp:'La batería almacena energía química que se convierte en eléctrica para accionar el motor de arranque. Una vez en marcha, el alternador proporciona la energía eléctrica.'},
  {id:172,cat:'mecanica',q:'¿Cuál es la función principal del alternador?',ops:['Arrancar el vehículo','Producir energía eléctrica cuando el motor está en marcha para recargar la batería y alimentar los sistemas','Enfriar la batería','Lubricar los pistones'],r:1,exp:'El alternador genera corriente eléctrica cuando el motor está funcionando, manteniendo la carga de la batería y alimentando las luces, radio, etc.'},
  {id:173,cat:'mecanica',q:'¿Qué significa si se enciende la luz roja de la presión de aceite en el tablero?',ops:['Que debe cambiar el aceite en el próximo mes','Que el motor está frío','Que la presión de aceite ha bajado a un nivel peligroso, debe detener el motor inmediatamente','Que el estanque de combustible está casi vacío'],r:2,exp:'La luz roja del aceite (una aceitera) indica que el motor no tiene lubricación suficiente. Se debe detener el motor inmediatamente para evitar que se funda (destrucción del motor).'},
  {id:174,cat:'mecanica',q:'¿Por qué es peligroso tener una presión de aire baja en los neumáticos?',ops:['Porque se gasta el centro de la banda de rodadura','Porque los neumáticos se sobrecalientan, pierden adherencia y aumenta el riesgo de reventón','Porque el vehículo se vuelve más liviano','No es peligroso, da mayor confort'],r:1,exp:'Una presión baja provoca que el neumático se flexione más, generando mucho calor que puede causar un reventón. Además, desgasta los bordes, aumenta el consumo y empeora la maniobrabilidad.'},
  {id:175,cat:'mecanica',q:'¿Qué función cumple el líquido refrigerante?',ops:['Enfriar el interior del habitáculo (aire acondicionado)','Absorber el calor del motor y disiparlo a través del radiador','Lubricar los frenos','Limpiar el parabrisas'],r:1,exp:'El líquido refrigerante (o agua con anticongelante) circula por el motor para absorber el calor extremo y luego pasa por el radiador donde el aire lo enfría.'},
  {id:176,cat:'mecanica',q:'Si al pisar el pedal del freno se siente "esponjoso" y se hunde casi hasta el fondo, es probable que:',ops:['Haya aire en el circuito de frenos o falta de líquido','Las pastillas estén nuevas','El freno de mano esté puesto','Los amortiguadores estén malos'],r:0,exp:'Un pedal de freno esponjoso suele indicar que ha entrado aire al sistema hidráulico (debe ser purgado) o que el nivel de líquido de frenos es peligrosamente bajo.'},
  {id:177,cat:'mecanica',q:'¿Para qué sirve el embrague en un vehículo con transmisión manual?',ops:['Para frenar más rápido','Para conectar y desconectar la energía del motor a la caja de cambios','Para aumentar la potencia del motor','Para dar arranque al vehículo'],r:1,exp:'El embrague interrumpe la transmisión de movimiento entre el motor y la caja de cambios, permitiendo engranar una nueva marcha sin dañar los engranajes.'},
  {id:178,cat:'mecanica',q:'¿Cada cuánto tiempo o kilometraje se debe cambiar el aceite del motor?',ops:['Solo cuando se encienda la luz roja del aceite','Una vez al año, sin importar los kilómetros','Según lo que indique el manual del fabricante del vehículo','Cuando el aceite se vea negro en la varilla'],r:2,exp:'Siempre se deben seguir las especificaciones del fabricante del vehículo, que indican intervalos de kilometraje (ej: cada 10.000 km) o de tiempo (ej: 1 vez al año), lo que ocurra primero.'},
  {id:179,cat:'mecanica',q:'¿Qué elemento del vehículo absorbe los impactos y las irregularidades del camino?',ops:['Los frenos ABS','La dirección hidráulica','El sistema de suspensión y amortiguadores','El chasis tubular'],r:2,exp:'La suspensión (resortes) y los amortiguadores son los encargados de absorber los golpes del camino, manteniendo las ruedas en contacto con el suelo y dando confort a los pasajeros.'},
  {id:180,cat:'mecanica',q:'¿Por qué no se debe abrir la tapa del radiador cuando el motor está caliente?',ops:['Porque el motor se enfriará muy rápido','Porque el líquido refrigerante está bajo gran presión y temperatura, pudiendo causar quemaduras graves al saltar','Porque se perderá la garantía del vehículo','Porque el líquido perderá su color'],r:1,exp:'El sistema de refrigeración trabaja presurizado. Si se abre la tapa con el motor caliente, la presión liberará bruscamente vapor y agua hirviendo hacia la cara y manos.'},

  // ===== SEGURIDAD =====
  {id:181,cat:'seguridad',q:'Si presencia un accidente de tránsito con heridos, ¿cuál es el orden correcto de actuación (conducta PAS)?',ops:['Proteger, Avisar, Socorrer','Avisar, Socorrer, Proteger','Socorrer, Avisar, Proteger','Preguntar, Ayudar, Salvar'],r:0,exp:'El protocolo universal PAS es: 1) Proteger el lugar (señalizar), 2) Avisar a los servicios de emergencia, 3) Socorrer a las víctimas (si se tienen los conocimientos básicos).'},
  {id:182,cat:'seguridad',q:'Al socorrer a un motociclista accidentado e inconsciente, usted debe:',ops:['Quitarle el casco rápidamente para que respire','Sentarlo en la calzada','Nunca quitarle el casco, mantenerlo inmovilizado y esperar a los equipos de rescate','Darle agua inmediatamente'],r:2,exp:'A un motociclista accidentado JAMÁS se le debe quitar el casco, a menos que sufra una parada cardiorrespiratoria y deba hacerle RCP, y solo con una técnica muy específica. Quitarlo mal puede causar lesiones medulares fatales.'},
  {id:183,cat:'seguridad',q:'¿Qué debe hacer si el neumático delantero derecho revienta (pincha violentamente) mientras conduce a alta velocidad?',ops:['Frenar a fondo inmediatamente','Girar el volante bruscamente hacia la izquierda','Sujetar firmemente el volante, levantar el pie del acelerador y frenar suavemente cuando haya recuperado el control','Tocar la bocina y acelerar'],r:2,exp:'Un reventón delantero tira el vehículo hacia ese lado. Debe aferrarse al volante con firmeza para mantener la trayectoria recta, no pisar el freno bruscamente, dejar que el auto pierda velocidad solo y luego frenar suave.'},
  {id:184,cat:'seguridad',q:'En caso de un incendio incipiente en el motor de su vehículo, usted debe:',ops:['Abrir el capó completamente y echar agua','Levantar el capó levemente, usar el extintor apuntando a la base de las llamas','Seguir conduciendo hasta un taller','Gritar pidiendo auxilio'],r:1,exp:'Si hay fuego en el motor, deténgase. NO abra el capó por completo ya que el oxígeno avivará las llamas. Ábralo un poco e introduzca el chorro del extintor hacia la base del fuego.'},
  {id:185,cat:'seguridad',q:'¿A quién debe llamar principalmente en Chile en caso de accidente de tránsito con heridos graves?',ops:['Al 131 (Ambulancia/SAMU) y al 133 (Carabineros)','Al 132 (Bomberos) únicamente','Al número de su aseguradora','A la municipalidad'],r:0,exp:'En un accidente con heridos se debe llamar al ABC de la emergencia: 131 Ambulancia (para los heridos), 133 Carabineros (para el control del tránsito y parte policial), y 132 Bomberos si hay personas atrapadas o derrame de combustible.'},
  {id:186,cat:'seguridad',q:'¿Hasta qué edad es obligatorio que los niños viajen en sistemas de retención infantil (sillas de auto) en Chile?',ops:['Hasta los 4 años','Hasta cumplir los 9 años (o estatura de 135 cm y 33 kg)','Hasta los 12 años','Solo si son bebés'],r:1,exp:'En Chile, todo niño menor de 9 años (o que mida menos de 135 cm y pese menos de 33 kg) debe viajar obligatoriamente en un Sistema de Retención Infantil adecuado a su peso, talla y edad.'},
  {id:187,cat:'seguridad',q:'¿Por qué los niños menores de 12 años deben ir siempre en los asientos traseros?',ops:['Para que no distraigan al conductor','Porque los airbags delanteros están diseñados para adultos y pueden matar a un niño al desplegarse','Para que tengan más espacio para jugar','No es obligatorio, pueden ir adelante si llevan cinturón'],r:1,exp:'Los menores de 12 años tienen prohibido ir en los asientos delanteros. El principal motivo es que el despliegue violento del airbag del copiloto puede ser letal para la fisionomía de un niño.'},
  {id:188,cat:'seguridad',q:'¿Qué es la seguridad ACTIVA del vehículo?',ops:['Los elementos que protegen a los ocupantes durante un choque (ej: airbag)','Los elementos que evitan que ocurra un accidente (ej: frenos ABS, luces, neumáticos, dirección)','El seguro del vehículo','El sistema de alarma contra robos'],r:1,exp:'La seguridad activa (o primaria) busca EVITAR que se produzca un accidente. Incluye: frenos, dirección, neumáticos, iluminación y suspensión.'},
  {id:189,cat:'seguridad',q:'¿Qué es la seguridad PASIVA del vehículo?',ops:['Los frenos','Los elementos diseñados para minimizar los daños a los ocupantes una vez que el accidente ya es inevitable (ej: cinturón, airbag, carrocería deformable, apoya cabezas)','El espejo retrovisor','Los neumáticos'],r:1,exp:'La seguridad pasiva (o secundaria) actúa DURANTE el choque para salvar vidas. Incluye el cinturón de seguridad, airbags, apoyacabezas y la carrocería con zonas de deformación programada.'},
  {id:190,cat:'seguridad',q:'¿Qué es el efecto latigazo o "whiplash"?',ops:['Un golpe lateral','Una lesión en el cuello que ocurre principalmente en colisiones por alcance (impactos por detrás), prevenible usando bien el apoyacabezas','Una falla en los frenos','El ruido de los neumáticos al derrapar'],r:1,exp:'El "latigazo cervical" ocurre en choques por detrás cuando la cabeza se va violentamente hacia atrás y luego hacia adelante. El apoyacabezas correctamente posicionado a la altura de las orejas es vital para evitarlo.'},

  // ===== CONDUCCION =====
  {id:191,cat:'manejo',q:'¿Por qué se requiere mayor distancia de detención cuando llueve?',ops:['Porque los neumáticos crecen con el agua','Porque el agua actúa como lubricante entre el neumático y el pavimento, disminuyendo la adherencia o agarre','Porque el vehículo se vuelve más pesado','Porque los frenos se dilatan'],r:1,exp:'El pavimento mojado reduce drásticamente la fricción (adherencia) de los neumáticos. Por esto, el vehículo resbalará por más tiempo al frenar, requiriendo el doble de distancia para detenerse que en pavimento seco.'},
  {id:192,cat:'manejo',q:'¿Qué es el "Aquaplaning" o hidroplaneo?',ops:['Lavar el auto a presión','Un defecto del motor','Cuando el neumático no logra desplazar el agua de la vía y el vehículo literalmente se desliza flotando sobre el agua, perdiendo el control de la dirección y los frenos','Frenar usando el agua de la lluvia'],r:2,exp:'El hidroplaneo ocurre cuando hay mucha agua en la vía o se va muy rápido; el diseño del neumático no alcanza a evacuar el agua y se forma una cuña de agua bajo la rueda. El auto pierde todo contacto con el suelo (flota) y queda incontrolable.'},
  {id:193,cat:'manejo',q:'¿Qué debe hacer si su vehículo entra en aquaplaning?',ops:['Frenar a fondo inmediatamente','Sujetar el volante, soltar suavemente el acelerador sin frenar, hasta que los neumáticos recuperen contacto con el asfalto','Girar el volante rápidamente para salir del charco','Acelerar para atravesar el agua más rápido'],r:1,exp:'Si frena o gira durante el aquaplaning, cuando las ruedas toquen el suelo el auto trompeará. Debe mantener firme la dirección y desacelerar lentamente hasta sentir que el auto recobra el peso (contacto con la vía).'},
  {id:194,cat:'manejo',q:'Al conducir de noche, usted debe cambiar a luces bajas (cruce) cuando:',ops:['Se cruce con un vehículo de frente o cuando se aproxime por detrás a otro vehículo (a menos de 200m)','Solo cuando entre a la ciudad','En carreteras iluminadas','Cuando el vehículo contrario le haga un cambio de luces'],r:0,exp:'Para no encandilar (cegar temporalmente) a otros conductores, debe poner las luces bajas cuando se acerque un vehículo en sentido contrario, y también cuando usted se acerque por detrás a otro vehículo (el reflejo en sus espejos lo encandilaría).'},
  {id:195,cat:'manejo',q:'Si un conductor que viene en sentido contrario le encandila con luces altas, usted debe:',ops:['Poner luces altas también para vengarse','Desviar la vista hacia la derecha (hacia el borde de la calzada) y guiarse por la línea blanca del borde, reduciendo la velocidad','Cerrar los ojos un segundo','Frenar bruscamente en el medio de la vía'],r:1,exp:'Nunca responda al encandilamiento con más luces altas; dos conductores ciegos es garantía de choque frontal. Disminuya la velocidad y guíe su trayectoria mirando hacia la línea del borde derecho de su calzada.'},
  {id:196,cat:'manejo',q:'¿Cuándo es más resbaladiza una calzada con lluvia?',ops:['Después de que lleva horas lloviendo','Cuando caen las primeras gotas, ya que el agua se mezcla con el polvo y el aceite del pavimento formando un barro resbaladizo','Cuando para de llover','Solo si el pavimento es de hormigón'],r:1,exp:'Las primeras gotas son las más peligrosas porque forman una fina capa de barro jabonoso (mezcla de agua, tierra y restos de aceite). Una vez que la lluvia es abundante, lava la vía y la adherencia mejora ligeramente (aunque sigue siendo pavimento mojado).'},
  {id:197,cat:'manejo',q:'¿Qué hacer si hay niebla densa?',ops:['Encender las luces altas para ver mejor','Encender luces bajas, los focos neblineros (si los tiene), reducir la velocidad y aumentar la distancia de seguimiento','No usar luces, solo guiarse por el auto de adelante','Apagar la radio'],r:1,exp:'Las luces altas en la niebla (o nieve) rebotan contra las gotas en suspensión y crean un muro blanco frente a usted que lo encandila a sí mismo. Use siempre luces bajas y neblineros.'},
  {id:198,cat:'manejo',q:'¿Cómo se debe tomar una curva de forma segura?',ops:['Frenando fuertemente en medio de la curva','Acelerando antes de entrar a la curva y frenando al salir','Frenar y reducir a la marcha adecuada ANTES de entrar a la curva, y una vez dentro acelerar suave y constantemente para mantener la tracción','En punto muerto'],r:2,exp:'La frenada siempre se hace en recta, antes de que empiecen a girar las ruedas. En medio de la curva se debe mantener una aceleración suave que pegue las ruedas al suelo y le dé tracción de salida.'},
  {id:199,cat:'manejo',q:'En caminos de alta montaña con nieve, ¿en qué ruedas se deben poner las cadenas?',ops:['En las ruedas traseras siempre','En todas las ruedas','En las ruedas motrices (las que reciben la fuerza del motor: las delanteras si es tracción delantera, las traseras si es tracción trasera)','En las ruedas del lado derecho'],r:2,exp:'Las cadenas se usan para tener tracción en hielo o nieve, por lo tanto, deben ir obligatoriamente en las ruedas motrices. En los autos con tracción integral (4x4) suele recomendarse en las delanteras por la dirección, o consultar el manual.'},
  {id:200,cat:'manejo',q:'¿Qué precaución especial debe tener al conducir con fuertes vientos laterales?',ops:['Sujetar el volante con firmeza, reducir la velocidad y estar atento a ráfagas al salir de zonas protegidas (como puentes o al adelantar a un camión)','Acelerar para pasar rápido la zona de viento','Apagar el motor','Conducir lo más pegado al borde izquierdo'],r:0,exp:'El viento lateral puede desplazar bruscamente el vehículo. Las ráfagas más peligrosas ocurren al salir de un túnel, en puentes, o cuando la protección que nos brindaba un camión desaparece al terminar de adelantarlo.'},
  
  // ===== NORMAS Y LEYES ======
  {id:201,cat:'normas',q:'¿A qué distancia de una esquina (cruce de calles) está prohibido estacionar?',ops:['A menos de 20 metros','A menos de 10 metros','A menos de 5 metros','A menos de 2 metros'],r:1,exp:'La Ley de Tránsito en Chile prohíbe estacionar a menos de 10 metros de una esquina (intersección) para no bloquear la visibilidad de los conductores que se aproximan al cruce.'},
  {id:202,cat:'normas',q:'¿A qué distancia de un grifo de bomberos (hidrante) está prohibido estacionar?',ops:['A menos de 5 metros','A menos de 10 metros','A menos de 1 metro','No hay restricción si el conductor se queda en el auto'],r:0,exp:'Está prohibido estacionar o detener el vehículo a menos de 5 metros de un grifo para incendio. Bomberos necesita espacio para conectar las mangueras rápidamente en una emergencia.'},
  {id:203,cat:'normas',q:'¿A qué distancia de una señal de PARE o CEDA EL PASO está prohibido estacionar?',ops:['A menos de 5 metros','A menos de 10 metros','A menos de 20 metros','A menos de 15 metros'],r:1,exp:'Está prohibido estacionar a menos de 10 metros de una señal de PARE, Ceda el Paso o semáforo, para evitar que el vehículo bloquee la visibilidad de la señal a otros conductores.'},
  {id:204,cat:'normas',q:'¿Qué dice la Ley Tolerancia Cero respecto a la conducción bajo la influencia del alcohol?',ops:['Es conducir con 0.1 a 0.2 gramos de alcohol por litro de sangre','Es conducir con 0.3 a 0.79 gramos de alcohol por litro de sangre. Implica la suspensión inmediata de la licencia.','Es conducir con más de 0.8 gramos de alcohol','No se considera delito, solo falta leve'],r:1,exp:'En Chile: "Bajo la influencia del alcohol" es de 0.3 a 0.79 g/L (se suspende la licencia por 3 meses si no hay daños). "Estado de ebriedad" es 0.8 g/L o más (delito, penas de cárcel y cancelación de licencia).'},
  {id:205,cat:'normas',q:'¿Qué es la Ley Emilia en Chile?',ops:['Ley que castiga el no usar cinturón de seguridad infantil','Ley que establece como delito fugarse del lugar de un accidente sin prestar ayuda, y endurece las penas de cárcel para quienes causen lesiones gravísimas o muerte manejando en estado de ebriedad','Ley sobre límites de velocidad en zonas escolares','Ley sobre uso de bicicletas'],r:1,exp:'La Ley Emilia penaliza duramente (con penas de cárcel efectivas mínimas de 1 año) a quienes manejen en estado de ebriedad causando lesiones graves/muerte. Además penaliza el darse a la fuga sin prestar auxilio (delito autónomo).'},
  {id:206,cat:'normas',q:'Si un conductor participa en un accidente con lesionados, la ley le obliga a:',ops:['Detener la marcha, prestar la ayuda que fuese posible y dar cuenta a la autoridad policial más cercana inmediatamente','Retirarse del lugar si no tuvo la culpa','Llamar al seguro y continuar su viaje','Mover los vehículos para no entorpecer el tránsito, sin esperar a carabineros'],r:0,exp:'Cualquier participante en un accidente con heridos está obligado por ley a: detenerse, prestar ayuda, y llamar/avisar a Carabineros de inmediato. El incumplimiento se considera "darse a la fuga", un delito castigado por la Ley Emilia.'},
  {id:207,cat:'normas',q:'¿Quién tiene la preferencia de paso en un cruce no regulado (sin semáforo ni señalizaciones)?',ops:['El vehículo que circula más rápido','El vehículo que llega por la derecha de usted','El vehículo que va derecho sin doblar','El vehículo más grande'],r:1,exp:'La regla universal de tránsito en Chile indica que en cruces sin señales ni semáforos, TODO vehículo que se aproxima al cruce debe ceder el paso al vehículo que se acerca por su lado DERECHO.'},
  {id:208,cat:'normas',q:'¿Cuándo pierde la preferencia el vehículo que viene por la derecha en un cruce no regulado?',ops:['Si el vehículo que viene por la izquierda es más grande','Si va a virar (doblar) en el cruce','Solo de noche','Nunca, la derecha siempre tiene preferencia absoluta'],r:1,exp:'La preferencia de la derecha se pierde en tres casos: 1) Si va a virar. 2) Si se incorpora a la vía desde un garaje/tierra. 3) En glorietas (rotondas), la preferencia la tiene el que ya circula adentro.'},
  {id:209,cat:'normas',q:'¿Qué debe hacer si al acercarse a un semáforo en verde, hay un taco (atasco) al otro lado de la intersección que le impediría cruzar por completo?',ops:['Avanzar rápido para no perder el verde','Detenerse antes de entrar al cruce y esperar que haya espacio, aunque el semáforo esté verde, para no bloquear la intersección','Avanzar y tocar la bocina','Doblar a la derecha obligatoriamente'],r:1,exp:'Es una infracción bloquear una intersección o un paso de cebra. Si no hay espacio suficiente al otro lado para su vehículo, NO DEBE avanzar al cruce, incluso si el semáforo está en verde.'},
  {id:210,cat:'normas',q:'¿De qué color son las luces de retroceso en los vehículos?',ops:['Rojas','Ámbar (naranjas)','Blancas','Azules'],r:2,exp:'Las luces de marcha atrás (retroceso) son obligatoriamente blancas. Sirven para iluminar el camino hacia atrás en la noche y para advertir a los demás (especialmente peatones) que el vehículo se moverá hacia atrás.'}
];

let content = fs.readFileSync('preguntas.js', 'utf8');

let nuevasLineas = '';
nuevas.forEach(p => {
  const ops = JSON.stringify(p.ops);
  nuevasLineas += '  { id:' + p.id + ', categoria:"' + p.cat + '", pregunta:"' + p.q + '", opciones:' + ops + ', respuesta:' + p.r + ', explicacion:"' + p.exp + '" },\n';
});

content = content.replace('];\n\nconst CATEGORIAS', nuevasLineas + '];\n\nconst CATEGORIAS');
fs.writeFileSync('preguntas.js', content, 'utf8');

let html = fs.readFileSync('index.html', 'utf8');
html = html.replace('170 preguntas', '210 preguntas');
fs.writeFileSync('index.html', html, 'utf8');

console.log('Agregadas ' + nuevas.length + ' preguntas.');
